dist: focal

language: python

sudo: true

addons:
  apt:
    packages:
      - libopenjp2-7-dev
      - libpng-dev

env:
  global:
    - DEPENDS="numpy pyproj"

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - python setup.py build
  - python setup.py install

script:
  - python setup.py test
