dist: bionic

language: python

sudo: false

addons:
  apt:
    packages:
      - libeccodes0
      - libeccodes-dev
      - libpng-dev

env:
  global:
    - DEPENDS="numpy pyproj"
    - JASPER_LIBDIR="/usr/lib/x86_64-linux-gnu"
    - JASPER_INCDIR="/usr/include"
    - PNG_LIBDIR="/usr/lib/x86_64-linux-gnu"
    - PNG_INCDIR="/usr/include"
    - ZLIB_LIBDIR="/usr/lib/x86_64-linux-gnu"
    - ZLIB_INCDIR="/usr/include"

python:
  - "3.6"
  - "3.7"
  - "3.8"
  #- "3.9"

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - python setup.py build
  - python setup.py install

#script:
#  - python test.py
