language: python

sudo: false

addons:
  apt:
    packages:
      - libeccodes
      - libeccodes-dev

env:
  global:
    - DEPENDS="numpy pyproj"

python:
  - "3.6"
  - "3.7"
  - "3.8"
  #- "3.9"

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - python setup.py build
  - python setup.py install

script:
  - python test.py
